cc_library(
  name = "materials",
  hdrs = glob(["*.h"]),
  srcs = glob(["*.cc"]),
  copts = ['-O2'],
  deps = ['//primitives:primitives', '//objects:objects', '//util:util'],
  visibility = ["//main:__pkg__"],
)